### ISSUE TITLE
Found a 404 on comicmeta.org

### ISSUE THREAD

**Issue by bmix** [comicmeta/ComicBookOntology#25]
The link is: http://comicmeta.org/issueOf

Also: CoverPage, SplashPage, Spread as Individuals of http://comicmeta.org/cbo/PageType

(I will come back to this issue, should I find more)

**Comment by seanpetiya** [comment]
This should finally be fixed. Thanks for bringing the issue to my attention, and I apologize for all of the extra chatter on this issue as I work to get the changes merged.
