### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by fedeb95** [comicmeta/ComicBookOntology#26]
Hi, first of all sorry if I say something stupid, but this is my first try with rdf. I'm trying to use this vocabulary in a web app for a simple collection of comics, featuring by now just series and copy. However I haven't found a way to represent a textual description given by the user, that could be either a review (like 'great comic') or the actual state of the comic, or even a combination of both. That is, a generic description that has a meaning to the user that wrote it. I read you suggested to use http://purl.org/dc/terms/description in another issue, could this be good?

Also I haven't found a property about a rating given by the user, like from 1 to 5 or similar, I only found "official" ratings. However I found that often readers like to give a review of how much they liked the comic (the story). Is there a suggested way of doing this?

Thank for your work anyway, this has been very useful to me.

**Comment by seanpetiya** [comment]
Great question, and I apologize for the delay! 

There's two approaches I think you can use here. First, as you suggested dcterms:description would work for a generic description. However, if you are looking for more specific descriptive types (e.g. ratings, comments, etc.); I would suggested also using schema.org. You could then implement types like [schema:Rating](https://schema.org/Rating) and [schema:Comment](https://schema.org/Comment) in your web app.

Here's an example bit of markup for a rating provided by a user:

```
  <rdf:Description rdf:about="http://example.org/issue/Daredevil_1964_67">
    <cbo:issueNumber>67</cbo:issueNumber>
    <cbo:publicationDate>1970-08</cbo:publicationDate>
    <schema:reviewRating>
      <rdf:Description rdf:about="http://example.org/issue/Daredevil_1964_67#comment1">
          <schema:ratingValue>5</schema:ratingValue>
          <schema:author>Bob</schema:author>
      </rdf:Description>
    </schema:reviewRating>
  </rdf:Description>
```

Glad you found the project useful! Good luck.
