### ISSUE TITLE
rdfs:isDefinedBy has rdfs:Resource as the range

### ISSUE THREAD

**Issue by smurp** [comicmeta/ComicBookOntology#31]
https://terms.tdwg.org/wiki/rdfs:isDefinedBy

Currently, throughout the ComicBookOntology when rdfs:isDefinedBy is used, the object is a string literal (ie with quotes around it) rather than being a Resource (ie with > and < around it ).

Thanks for the ontology, nice work!

**Comment by seanpetiya** [comment]
Updated all rdfs:isDefinedBy references to IRIs from literals. Thanks for bringing the issue to my attention.
