### ISSUE TITLE
About the pageNumber property

### ISSUE THREAD

**Issue by elkym** [comicmeta/ComicBookOntology#40]
It seems to have been superseded by the pageCount property... maybe I'm wrong?

If pageNumber is a distinct property-- it seems that it would be a literal field that can be used to indicate a particular page number within a published comic would be... helpful to me.

Or someone can explain instead how this property is intended to function?

**Comment by seanpetiya** [comment]
This looks like a bug to me, the label for `cbo:pageNumber` is incorrect. And the definition of `cbo:pageNumber` should be updated to read something like "The number of a page in a comic publication."

It is intended to be used as you describe, a literal value that indicates a particular page's number.

Good find, I will make sure to get this issue resolved.

**Comment by elkym** [comment]
Oh that's awesome. While I'm sorry that you have a bug to fix, ... I'm glad that you have a bug to fix. *chuckle

**Comment by seanpetiya** [comment]
Closing issue; label and definition updated as discussed.
